import { type NextPage } from "next";
import Head from "next/head";
import { Map } from "~/components/map";
import { H1, H2 } from "~/components/typography";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>
          Funro Map - The 150 best rated mountains in Scotland of any size
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="fixed left-0 top-0 z-50 m-0 flex w-full flex-col items-center bg-sky-950 p-3 text-white shadow-lg">
          <H1>The Funro Map</H1>
          <H2>{"Because size isn't everything..."}</H2>
        </div>
        <Map />
      </main>
    </>
  );
};

export default Home;
