import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { InfoModal } from "~/components/info-modal";
import { Map } from "~/components/map/map";
import { H1, H2 } from "~/components/typography";
import { LocalStorageKeys } from "~/constants";

const Home: NextPage = () => {
  const [showInfoModal, setShowInfoModal] = useState(false);

  useEffect(() => {
    const infoModalSeen = localStorage.getItem(
      LocalStorageKeys.INFO_MODAL_SEEN
    );
    if (!infoModalSeen) {
      setShowInfoModal(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>
          Funro Map - The 150 best rated mountains in Scotland of any size
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="fixed left-0 top-0 z-50 m-0 flex w-full flex-col items-center bg-sky-950 p-3 text-white shadow-lg">
          <H1>The Funro Map</H1>
          <H2>{"Because size isn't everything..."}</H2>
        </div>
        <Map />
        <InfoModal
          show={showInfoModal}
          onContinue={() => {
            localStorage.setItem(LocalStorageKeys.INFO_MODAL_SEEN, "true");
            setShowInfoModal(false);
          }}
        />
      </main>
    </>
  );
};

export default Home;
