import { type NextPage } from "next";
import Head from "next/head";

const Privacy: NextPage = () => {
  return (
    <>
      <Head>
        <title>
          Funro Map - The 150 best rated mountains in Scotland of any size
        </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Privacy Policy</h1>
        <p>
          This Privacy Policy explains how we collect, use, and protect your
          personal information when you visit our website.{" "}
        </p>
        <h2>Information Collection and Use</h2>
        <p>
          {" "}
          We do not collect or store any personal information about our website
          visitors. We respect your privacy and are committed to ensuring that
          your personal information is protected. However, we use Firebase
          Analytics to collect and analyze non-personal, aggregated data about
          user interactions with our website. Firebase Analytics helps us
          understand user behavior and improve the user experience. The data
          collected includes: - Information about your device, such as device
          type, operating system, and browser - Your IP address (anonymized) -
          User interactions with the website, such as pageviews and clicks -
          Other technical data related to website usage We do not attempt to
          identify individual users through Firebase Analytics, and we do not
          link this data to any personally identifiable information.{" "}
        </p>
        <h2>Cookies</h2>
        <p>
          {" "}
          Our website may use cookies to enhance your experience. Cookies are
          small text files that are stored on your device when you visit our
          website. They help us improve the functionality and performance of our
          website. You can choose to accept or decline cookies in your browser
          settings.{" "}
        </p>
        <h2>Third-Party Websites</h2>
        <p>
          {" "}
          Our website may contain links to external websites or services that
          are not operated by us. We are not responsible for the privacy
          practices or content of these external websites. We encourage you to
          review the privacy policies of those websites.{" "}
        </p>
        <h2>{"Children's Privacy"}</h2>
        <p>
          {" "}
          Our website does not knowingly collect or store personal information
          from individuals under the age of 13. If you believe that a child has
          provided us with personal information, please contact us, and we will
          take appropriate action to remove such information.{" "}
        </p>
        <h2>Changes to this Privacy Policy</h2>
        <p>
          {" "}
          We may update this Privacy Policy to reflect changes to our practices
          or for legal or regulatory reasons. We encourage you to check this
          page periodically for any updates. Your continued use of our website
          constitutes your acceptance of any revised Privacy Policy.{" "}
        </p>
        <h2>Contact Us</h2>
        <p>
          {" "}
          If you have any questions or concerns about our Privacy Policy or the
          use of Firebase Analytics on our website, please contact us at
          [contact@email.com]. This Privacy Policy was last updated on [Date of
          Last Update]. --- Please note that while this template provides a
          starting point for a privacy policy, you should adapt it to your
          specific needs and consult with a legal professional to ensure it
          complies with applicable laws and regulations. Additionally, be sure
          to provide accurate contact information for users to reach out with
          privacy-related concerns or inquiries.
        </p>
      </main>
    </>
  );
};

export default Privacy;
