name: Install Node and dependencies
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Get Node version
      id: node-version
      run: |
        echo "version=$(node --version)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        key: node_modules-${{ runner.os }}-${{ steps.node-version.outputs.version}}-${{ hashFiles('yarn.lock') }}
        path: |
          node_modules
          ~/.cache/Cypress

    - name: Install Yarn 4
      run: |
        corepack prepare yarn@4 --activate
        yarn set version 4
      shell: bash

    - name: Install dependencies
      run: yarn --immutable
      shell: bash
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
