name: Main
on:
  # push:
  #   branches:
  #     - main
  pull_request:
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/install

      - name: Build
        run: |
          curl -sL firebase.tools | bash
          yarn build
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
