name: Main
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/install

      - name: Install Firebase
        run: curl -sL firebase.tools | bash

      - name: Build
        run: yarn build

      - name: Deploy
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
