name: Main
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install

      - name: Install Firebase
        run: curl -sL firebase.tools | bash

      - name: Build
        run: yarn build

      - name: Deploy
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    needs: build_and_deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          # All env vars must be prefixed with CYPRESS_ https://github.com/cypress-io/github-action
          CYPRESS_TEST_URL: "https://funromap.web.app"
        with:
          wait-on: https://funromap.web.app
