name: PR
on:
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: LS
        run: ls -a .

      - uses: ./.github/actions/install

      - name: Lint
        run: yarn lint

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - uses: ./.github/actions/install

  #     - name: Build
  #       run: yarn build
