name: PR
on:
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/install

      - name: Lint
        run: yarn lint --max-warnings=0

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_TEST_URL: "http://localhost:3000"
        with:
          build: yarn build
          start: npx serve@latest out
          wait-on: http://localhost:3000

  # Unnecessary if you build during E2E job
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - uses: ./.github/actions/install

  #     - name: Build
  #       run: yarn build
